### ISSUE TITLE
Number of retrieved observations maximized?

### ISSUE THREAD

**Issue by liekeverhelst** [AKSW/cubeviz.ontowiki#199]
Hi AKSW
We have a Docker deployment of Cubeviz running. The dataset that we have has quite a large number of dimension values per dimension. (one dimension can have more than 100 values, two other dimensions can have 6, resp. values each). We notice that not all observations are retrieved in the graph, even though they are in the dataset. (If you make a different combination, the values that were missing before are displayed).
Is there a parameter somewhere that sets this maximum of observations?
If neccessary we can send the data directly to you.
Thanks, Lieke

**Comment by k00ni** [comment]
Hey, CubeViz has a restriction to only load 1000 observations, if i remember it right. And there is also a restriction when it selects dimension elements. Could you describe the metrics of your dataset please? Number of observations, datasets, dimensions, dimension elements per dimension, ...

Regards

**Comment by liekeverhelst** [comment]
Hi we have one dataset, one DSD, 10360 obs in dataset, 6 dimensions (of which only 3 currently in use) , one dimension has more than 100 elements (limited to 100 in the UI I think), the other two dimensions have 5 resp 6 elements.

**Comment by k00ni** [comment]
I checked the related file Query.php and found that only 250 observations will be loaded and displayed later on. You could play around with that code line [here](https://github.com/AKSW/cubeviz.ontowiki/blob/master/classes/DataCube/Query.php#L708) and see, how CubeViz reacts. We decided to limit the system to avoid problems in the charts later on.

**Comment by k00ni** [comment]
Hey @liekeverhelst, how is it going?

**Comment by liekeverhelst** [comment]
Hi @k00ni thanks we are currently testing. I am not the sysadmin of the box so have to wait for the guy to implement the change in Query.php. Will keep you posted!

**Comment by liekeverhelst** [comment]
Hi @k00ni , changing the parameter improves it. Thanks!

**Comment by k00ni** [comment]
You welcome :)
